export const ACTIVITY_CONFIG = {
  BA: [
    { label: 'Client Discovery Call',          multiplier: 1.75 },
    { label: 'Requirements Gathering',          multiplier: 1.80 },
    { label: 'Client Demo / Presentation',      multiplier: 1.65 },
    { label: 'Stakeholder Meeting',             multiplier: 1.55 },
    { label: 'Client UAT Walkthrough',          multiplier: 1.70 },
    { label: 'BA Documentation / BRD',          multiplier: 1.40 },
    { label: 'UAT Coordination & Sign-off',     multiplier: 1.45 },
    { label: 'Follow-up Emails / Async Comms',  multiplier: 1.35 },
    { label: 'Jira Ticket Creation & Grooming', multiplier: 1.35 },
  ],
  DEV: [
    { label: 'Feature Development',             multiplier: 1.40 },
    { label: 'Bug Investigation & Fix',         multiplier: 1.55 },
    { label: 'API Integration',                 multiplier: 1.45 },
    { label: 'Database Work / Migration',       multiplier: 1.45 },
    { label: 'Code Review',                     multiplier: 1.35 },
    { label: 'Refactoring / Tech Debt',         multiplier: 1.40 },
    { label: 'Environment Setup / Config',      multiplier: 1.50 },
    { label: 'Deployment & Release',            multiplier: 1.55 },
    { label: 'CRM / Platform Customisation',    multiplier: 1.45 },
    { label: 'Third-party Integration',         multiplier: 1.50 },
    { label: 'Workflow / Automation Build',     multiplier: 1.40 },
    { label: 'Functional Testing',              multiplier: 1.40 },
    { label: 'Regression Testing',              multiplier: 1.38 },
    { label: 'Bug Reporting & Retesting',       multiplier: 1.45 },
    { label: 'Cross-browser / Device Testing',  multiplier: 1.40 },
    { label: 'UAT Support',                     multiplier: 1.45 },
    { label: 'Performance / Load Testing',      multiplier: 1.50 },
  ],
  US: [
    { label: 'Client Discovery Call',           multiplier: 1.75 },
    { label: 'Stakeholder Meeting',             multiplier: 1.55 },
    { label: 'Client Demo / Presentation',      multiplier: 1.65 },
    { label: 'Sprint Planning',                 multiplier: 1.40 },
    { label: 'Status Update / Reporting',       multiplier: 1.35 },
    { label: 'Risk Assessment',                 multiplier: 1.50 },
    { label: 'Training / Knowledge Transfer',   multiplier: 1.45 },
    { label: 'Research & Feasibility Study',    multiplier: 1.50 },
    { label: 'Internal Team Discussion',        multiplier: 1.35 },
  ],
  PM: [
    { label: 'Sprint Planning / Grooming',      multiplier: 1.40 },
    { label: 'Daily Standup & Sync',            multiplier: 1.35 },
    { label: 'Status Update / Reporting',       multiplier: 1.35 },
    { label: 'Risk Assessment & Mitigation',    multiplier: 1.50 },
    { label: 'Training / Knowledge Transfer',   multiplier: 1.45 },
    { label: 'Research & Feasibility Study',    multiplier: 1.50 },
    { label: 'Internal Team Discussion',        multiplier: 1.35 },
    { label: 'Follow-up Emails / Async Comms',  multiplier: 1.35 },
  ],
};
